server:
  servlet:
    context-path: /api

application:
  jwt:
    key: LJjGo0mnwGVs7RVj6F3X1t0Yq1JtPxo9A9m00G0HeJY=
  encryption:
    secretKey: rEMi9yyfvH0AfSOfgqvSeE8h0GLQaflu7VxRrcExTGo=
    algorithm: AES
    cipherMode: AES/ECB/PKCS5Padding
  alert:
    ttl: 25
    waiting: 20
    block: 10
    eBlock: 60
    total: 120
    threshold: 0.4
  emergency:
    mail: 2004.01035@manas.edu.kg

spring:
  application:
    name: "cloud"
  datasource:
    url: jdbc:postgresql://localhost:5434/cloud_iot
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  cache:
    type: simple
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: 28112002akn@gmail.com
    password: fkmeodoueagkcrri
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    kg.edu.manas.cloud: DEBUG
